# Generated by Django 5.2.4 on 2025-07-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["done", "created_at"]},
        ),
        migrations.RenameField(
            model_name="task",
            old_name="create_time",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="is_done",
            new_name="done",
        ),
    ]
